---
title: Horsham Digital Hub
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Digital@river.red
description: |
  Horsham Digital Group
url: http://horsham.digital
twitter_username: horshamdigital
github_username: horshamdigital
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
